language: java

env:
  matrix:
    - DUMMY=run-as-is
    - PROFILE=spring-data-next
    - PROFILE=spring-data-next-releasetrain
    - PROFILE=spring-data-next-releasetrain-released
    - BOOT=2.3.2.BUILD-SNAPSHOT PROFILE=spring-data-next-releasetrain
    - BOOT=2.3.2.BUILD-SNAPSHOT PROFILE=spring-data-next-releasetrain-released

services:
  - redis-server
  - docker

cache:
  directories:
    - $HOME/.m2

install: true

script:
 - git clone https://github.com/spring-projects/spring-data-examples.git
 - cp -f settings.xml $HOME/.m2/settings.xml
 - ./run.sh
