language: java

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
    - oracle-java8-installer

env:
  matrix:
    - PROFILE=ci
    - PROFILE=spring5

services:
  - redis-server

cache:
  directories:
    - $HOME/.m2

sudo: false

install: true

script: "mvn clean dependency:list test -P${PROFILE} -U -Dsort -Dmaven.test.redirectTestOutputToFile=true -B"
